services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    ports:
      - "${NODE_RED_PORT}:1880"
    environment:
      - TZ=Europe/Paris
    depends_on:
      - mongodb
    volumes:
      - nodered_data:/data

volumes:
  nodered_data:
