version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped


  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "${NODE_RED_PORT}:1880"
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      - mongodb
    restart: unless-stopped


volumes:
  mongo_data:
