services:
  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: always
    user: "1000:1000"
    ports:
      - "${NODE_RED_PORT:-1880}:1880"
    environment:
      - TZ=Europe/Paris
    depends_on:
      - mongodb
    volumes:
      - nodered_data:/data
    security_opt:
      - apparmor:unconfined
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  nodered_data:
