version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/data
    environment:
      - TZ=Europe/Paris

volumes:
  mongo_data:
